name: Build and Deploy Static Web App to Azure

on:
  push:
    branches: [ "main" ]  # Cambia "develop" si no la necesitas
  pull_request:
    branches: [ "main" ]  # Cambia "develop" si no la necesitas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ AZURE_STATIC_WEB_APP_TOKEN }}  # Token de despliegue
          action: 'upload'
          app_location: './build'  
          api_location: ''          
          output_location: './build'  
